# Generated by Django 4.2.5 on 2024-07-11 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('duedate', models.DateField()),
                ('duetime', models.TimeField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
